# Generated by Django 5.2.3 on 2025-06-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recyclers',
            fields=[
                ('recycler_id', models.CharField(help_text='Primary key, unique ID for each user', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Full name of the user', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Unique, nullable email address', max_length=100, null=True, unique=True)),
                ('phone_number', models.IntegerField(blank=True, help_text='Unique, nullable phone number', null=True, unique=True)),
                ('password', models.CharField(help_text='Encrypted password', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Account creation timestamp')),
            ],
        ),
    ]
