# Generated by Django 5.2.3 on 2025-06-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('points_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('points_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
