# Generated by Django 5.2.3 on 2025-06-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('phone_number', models.IntegerField(unique=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=50)),
                ('material_description', models.CharField(max_length=100)),
            ],
        ),
    ]
